### ISSUE TITLE
No trim line

### ISSUE THREAD

**Issue by Gemorroj** [mvar/log-parser#2]
[LogIterator.php#L103](../blob/master/src/LogIterator.php#L103)
for example mysql log:
```
2016-03-01T22:22:37.800861Z 0 [Note] InnoDB: Progress in MB:
 100 200
```
For the analysis, it is necessary to preserve the space before the `100`.

**Comment by Gemorroj** [comment]
Perhaps a good solution would be to add a constructor parameter, by analogy with `$skipEmptyLines`

**Comment by mvar** [comment]
Hi. I will check this later. Probably it would be fine to trim new lines only. If I remember correctly, that string comes with new line at the end.

**Comment by mvar** [comment]
Hi. I have changed current logic to trim only new line characters.

https://github.com/mvar/log-parser/releases/tag/v1.1.0
